import { Tenant } from './Tenant.js';
import { TenantSetting } from './TenantSetting.js';
import { User } from './User.js';
import { UserSession } from './UserSession.js';
import { Invitation } from './Invitation.js';
import { PasswordResetToken } from './PasswordResetToken.js';
import { Department } from './Department.js';
import { Employee } from './Employee.js';
import { EmployeeSalaryStructure } from './EmployeeSalaryStructure.js';
import { EmployeeDocument } from './EmployeeDocument.js';
import { AttendanceRecord } from './AttendanceRecord.js';

Tenant.hasOne(TenantSetting, { foreignKey: 'tenantId', as: 'settings' });
Tenant.hasMany(User, { foreignKey: 'tenantId', as: 'users' });
Tenant.hasMany(UserSession, { foreignKey: 'tenantId', as: 'sessions' });
Tenant.hasMany(Invitation, { foreignKey: 'tenantId', as: 'invitations' });
Tenant.hasMany(Department, { foreignKey: 'tenantId', as: 'departments' });
Tenant.hasMany(Employee, { foreignKey: 'tenantId', as: 'employees' });
User.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
User.hasMany(UserSession, { foreignKey: 'userId', as: 'sessions' });
User.hasMany(PasswordResetToken, { foreignKey: 'userId', as: 'passwordResetTokens' });
UserSession.belongsTo(User, { foreignKey: 'userId', as: 'user' });
Invitation.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
Invitation.belongsTo(User, { foreignKey: 'invitedBy', as: 'inviter' });
PasswordResetToken.belongsTo(User, { foreignKey: 'userId', as: 'user' });
Department.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
Department.belongsTo(Employee, { foreignKey: 'headEmployeeId', as: 'head' });
Department.hasMany(Employee, { foreignKey: 'departmentId', as: 'employees' });
Employee.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
Employee.belongsTo(User, { foreignKey: 'userId', as: 'user' });
Employee.belongsTo(Department, { foreignKey: 'departmentId', as: 'department' });
Employee.hasMany(EmployeeSalaryStructure, { foreignKey: 'employeeId', as: 'salaryStructures' });
Employee.hasMany(EmployeeDocument, { foreignKey: 'employeeId', as: 'documents' });
EmployeeSalaryStructure.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
EmployeeDocument.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
EmployeeDocument.belongsTo(User, { foreignKey: 'uploadedBy', as: 'uploader' });
Employee.hasMany(AttendanceRecord, { foreignKey: 'employeeId', as: 'attendanceRecords' });
AttendanceRecord.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
AttendanceRecord.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });

export { Tenant, TenantSetting, User, UserSession, Invitation, PasswordResetToken, Department, Employee, EmployeeSalaryStructure, EmployeeDocument, AttendanceRecord };
