import { Tenant } from './Tenant.js';
import { TenantSetting } from './TenantSetting.js';
import { User } from './User.js';
import { UserSession } from './UserSession.js';
import { Invitation } from './Invitation.js';
import { PasswordResetToken } from './PasswordResetToken.js';
import { Department } from './Department.js';
import { Employee } from './Employee.js';
import { EmployeeSalaryStructure } from './EmployeeSalaryStructure.js';
import { SalaryComponent } from './SalaryComponent.js';
import { EmployeeSalaryComponent } from './EmployeeSalaryComponent.js';
import { Bonus } from './Bonus.js';
import { EmployeeDeduction } from './EmployeeDeduction.js';
import { EmployeeLoan } from './EmployeeLoan.js';
import { LoanInstallment } from './LoanInstallment.js';
import { EmployeeBankAccount } from './EmployeeBankAccount.js';
import { EmployeeTaxConfiguration } from './EmployeeTaxConfiguration.js';
import { PayrollAdjustment } from './PayrollAdjustment.js';
import { PerformanceCycle } from './PerformanceCycle.js';
import { PerformanceCriterion } from './PerformanceCriterion.js';
import { PerformanceTemplate } from './PerformanceTemplate.js';
import { PerformanceTemplateCriterion } from './PerformanceTemplateCriterion.js';
import { PerformanceGoal } from './PerformanceGoal.js';
import { PerformanceEvidence } from './PerformanceEvidence.js';
import { PerformanceReview } from './PerformanceReview.js';
import { PerformanceReviewScore } from './PerformanceReviewScore.js';
import { PerformanceScoreSnapshot } from './PerformanceScoreSnapshot.js';
import { PerformanceRatingBand } from './PerformanceRatingBand.js';
import { PerformanceEquivalenceSetting } from './PerformanceEquivalenceSetting.js';
import { PerformanceEquivalenceGroup } from './PerformanceEquivalenceGroup.js';
import { PerformanceEquivalenceMember } from './PerformanceEquivalenceMember.js';
import { PerformanceSignatureRule } from './PerformanceSignatureRule.js';
import { PerformanceSignature } from './PerformanceSignature.js';
import { PromotionProfile } from './PromotionProfile.js';
import { PromotionReadinessCriterion } from './PromotionReadinessCriterion.js';
import { EmployeePromotionAssessment } from './EmployeePromotionAssessment.js';
import { PerformanceReward } from './PerformanceReward.js';
import { PerformanceCalibrationDecision } from './PerformanceCalibrationDecision.js';
import { PerformanceCalibrationSetting } from './PerformanceCalibrationSetting.js';
import { PerformanceAppraisalExplanation } from './PerformanceAppraisalExplanation.js';
import { PerformanceFairnessFlag } from './PerformanceFairnessFlag.js';
import { EmployeeDocument } from './EmployeeDocument.js';
import { AttendanceRecord } from './AttendanceRecord.js';
import { LeaveType } from './LeaveType.js';
import { LeaveBalance } from './LeaveBalance.js';
import { LeaveRequest } from './LeaveRequest.js';
import { Notification } from './Notification.js';
import { PayrollRun } from './PayrollRun.js';
import { PayrollItem } from './PayrollItem.js';
import { PayrollItemLine } from './PayrollItemLine.js';
import { AuditLog } from './AuditLog.js';
import { EmployeeHistoryEvent } from './EmployeeHistoryEvent.js';
import { HistoricalPerformanceRecord } from './HistoricalPerformanceRecord.js';
import { PerformanceCycleLink } from './PerformanceCycleLink.js';

Tenant.hasOne(TenantSetting, { foreignKey: 'tenantId', as: 'settings' });
Tenant.hasMany(User, { foreignKey: 'tenantId', as: 'users' });
Tenant.hasMany(UserSession, { foreignKey: 'tenantId', as: 'sessions' });
Tenant.hasMany(Invitation, { foreignKey: 'tenantId', as: 'invitations' });
Tenant.hasMany(Department, { foreignKey: 'tenantId', as: 'departments' });
Tenant.hasMany(Employee, { foreignKey: 'tenantId', as: 'employees' });
Tenant.hasMany(SalaryComponent, { foreignKey: 'tenantId', as: 'salaryComponents' });
Tenant.hasMany(Bonus, { foreignKey: 'tenantId', as: 'bonuses' });
Tenant.hasMany(EmployeeDeduction, { foreignKey: 'tenantId', as: 'employeeDeductions' });
Tenant.hasMany(EmployeeLoan, { foreignKey: 'tenantId', as: 'employeeLoans' });
Tenant.hasMany(EmployeeBankAccount, { foreignKey: 'tenantId', as: 'bankAccounts' });
Tenant.hasMany(EmployeeTaxConfiguration, { foreignKey: 'tenantId', as: 'taxConfigurations' });
Tenant.hasMany(PayrollAdjustment, { foreignKey: 'tenantId', as: 'payrollAdjustments' });
Tenant.hasMany(PerformanceCycle, { foreignKey: 'tenantId', as: 'performanceCycles' });
Tenant.hasMany(PerformanceCriterion, { foreignKey: 'tenantId', as: 'performanceCriteria' });
Tenant.hasMany(PerformanceTemplate, { foreignKey: 'tenantId', as: 'performanceTemplates' });
Tenant.hasMany(PerformanceGoal, { foreignKey: 'tenantId', as: 'performanceGoals' });
Tenant.hasMany(PerformanceEvidence, { foreignKey: 'tenantId', as: 'performanceEvidence' });
Tenant.hasMany(PerformanceReview, { foreignKey: 'tenantId', as: 'performanceReviews' });
Tenant.hasMany(PerformanceScoreSnapshot, { foreignKey: 'tenantId', as: 'performanceScoreSnapshots' });
Tenant.hasMany(PerformanceRatingBand, { foreignKey: 'tenantId', as: 'performanceRatingBands' });
Tenant.hasOne(PerformanceEquivalenceSetting, { foreignKey: 'tenantId', as: 'performanceEquivalenceSetting' });
Tenant.hasMany(PerformanceEquivalenceGroup, { foreignKey: 'tenantId', as: 'performanceEquivalenceGroups' });
Tenant.hasMany(PerformanceSignatureRule, { foreignKey: 'tenantId', as: 'performanceSignatureRules' });
Tenant.hasMany(PerformanceSignature, { foreignKey: 'tenantId', as: 'performanceSignatures' });
Tenant.hasMany(PromotionProfile, { foreignKey: 'tenantId', as: 'promotionProfiles' });
Tenant.hasMany(EmployeePromotionAssessment, { foreignKey: 'tenantId', as: 'promotionAssessments' });
Tenant.hasMany(PerformanceReward, { foreignKey: 'tenantId', as: 'performanceRewards' });
Tenant.hasMany(PerformanceCalibrationDecision, { foreignKey: 'tenantId', as: 'performanceCalibrationDecisions' });
Tenant.hasOne(PerformanceCalibrationSetting, { foreignKey: 'tenantId', as: 'performanceCalibrationSetting' });
Tenant.hasMany(PerformanceAppraisalExplanation, { foreignKey: 'tenantId', as: 'performanceAppraisalExplanations' });
Tenant.hasMany(PerformanceFairnessFlag, { foreignKey: 'tenantId', as: 'performanceFairnessFlags' });
User.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
User.hasMany(UserSession, { foreignKey: 'userId', as: 'sessions' });
User.hasMany(PasswordResetToken, { foreignKey: 'userId', as: 'passwordResetTokens' });
UserSession.belongsTo(User, { foreignKey: 'userId', as: 'user' });
Invitation.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
Invitation.belongsTo(User, { foreignKey: 'invitedBy', as: 'inviter' });
PasswordResetToken.belongsTo(User, { foreignKey: 'userId', as: 'user' });
Department.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
Department.belongsTo(Employee, { foreignKey: 'headEmployeeId', as: 'head' });
Department.hasMany(Employee, { foreignKey: 'departmentId', as: 'employees' });
Employee.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
Employee.belongsTo(User, { foreignKey: 'userId', as: 'user' });
Employee.belongsTo(Department, { foreignKey: 'departmentId', as: 'department' });
Employee.belongsTo(Employee, { foreignKey: 'managerEmployeeId', as: 'manager' });
Employee.hasMany(Employee, { foreignKey: 'managerEmployeeId', as: 'directReports' });
Employee.hasMany(EmployeeHistoryEvent, { foreignKey: 'employeeId', as: 'historyEvents' });
Employee.hasMany(HistoricalPerformanceRecord, { foreignKey: 'employeeId', as: 'historicalPerformance' });
EmployeeHistoryEvent.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
HistoricalPerformanceRecord.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
HistoricalPerformanceRecord.belongsTo(PerformanceCycle, { foreignKey: 'cycleId', as: 'cycle' });
PerformanceCycle.hasMany(PerformanceCycleLink, { foreignKey: 'previousCycleId', as: 'nextCycleLinks' });
PerformanceCycle.hasMany(PerformanceCycleLink, { foreignKey: 'currentCycleId', as: 'previousCycleLinks' });
PerformanceCycleLink.belongsTo(PerformanceCycle, { foreignKey: 'previousCycleId', as: 'previousCycle' });
PerformanceCycleLink.belongsTo(PerformanceCycle, { foreignKey: 'currentCycleId', as: 'currentCycle' });
Employee.hasMany(EmployeeSalaryStructure, { foreignKey: 'employeeId', as: 'salaryStructures' });
Employee.hasMany(EmployeeDocument, { foreignKey: 'employeeId', as: 'documents' });
EmployeeSalaryStructure.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
SalaryComponent.hasMany(EmployeeSalaryComponent, { foreignKey: 'componentId', as: 'assignments' });
EmployeeSalaryComponent.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
EmployeeSalaryComponent.belongsTo(SalaryComponent, { foreignKey: 'componentId', as: 'component' });
Employee.hasMany(Bonus, { foreignKey: 'employeeId', as: 'bonuses' });
Bonus.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
Employee.hasMany(EmployeeDeduction, { foreignKey: 'employeeId', as: 'deductions' });
EmployeeDeduction.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
Employee.hasMany(EmployeeLoan, { foreignKey: 'employeeId', as: 'loans' });
EmployeeLoan.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
EmployeeLoan.hasMany(LoanInstallment, { foreignKey: 'loanId', as: 'installments' });
LoanInstallment.belongsTo(EmployeeLoan, { foreignKey: 'loanId', as: 'loan' });
LoanInstallment.belongsTo(PayrollItem, { foreignKey: 'payrollItemId', as: 'payrollItem' });
Employee.hasMany(EmployeeBankAccount, { foreignKey: 'employeeId', as: 'bankAccounts' });
EmployeeBankAccount.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
Employee.hasMany(EmployeeTaxConfiguration, { foreignKey: 'employeeId', as: 'taxConfigurations' });
EmployeeTaxConfiguration.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
PayrollRun.hasMany(PayrollAdjustment, { foreignKey: 'payrollRunId', as: 'adjustments' });
PayrollAdjustment.belongsTo(PayrollRun, { foreignKey: 'payrollRunId', as: 'run' });
PerformanceCycle.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
PerformanceCycle.belongsTo(User, { foreignKey: 'createdBy', as: 'creator' });
PerformanceCriterion.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
PerformanceTemplate.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
PerformanceTemplate.belongsTo(User, { foreignKey: 'createdBy', as: 'creator' });
PerformanceTemplate.hasMany(PerformanceTemplateCriterion, { foreignKey: 'templateId', as: 'criteria' });
PerformanceTemplateCriterion.belongsTo(PerformanceTemplate, { foreignKey: 'templateId', as: 'template' });
PerformanceTemplateCriterion.belongsTo(PerformanceCriterion, { foreignKey: 'criterionId', as: 'criterion' });
PerformanceCriterion.hasMany(PerformanceTemplateCriterion, { foreignKey: 'criterionId', as: 'templateAssignments' });
PerformanceCycle.hasMany(PerformanceGoal, { foreignKey: 'cycleId', as: 'goals' });
PerformanceGoal.belongsTo(PerformanceCycle, { foreignKey: 'cycleId', as: 'cycle' });
PerformanceGoal.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
PerformanceGoal.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
PerformanceGoal.belongsTo(Employee, { foreignKey: 'managerId', as: 'manager' });
PerformanceGoal.belongsTo(User, { foreignKey: 'createdBy', as: 'creator' });
PerformanceEvidence.belongsTo(PerformanceCycle, { foreignKey: 'cycleId', as: 'cycle' });
PerformanceEvidence.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
PerformanceEvidence.belongsTo(PerformanceGoal, { foreignKey: 'goalId', as: 'goal' });
PerformanceEvidence.belongsTo(PerformanceCriterion, { foreignKey: 'criterionId', as: 'criterion' });
PerformanceEvidence.belongsTo(User, { foreignKey: 'submittedBy', as: 'submitter' });
PerformanceEvidence.belongsTo(User, { foreignKey: 'verifiedBy', as: 'verifier' });
PerformanceReview.belongsTo(PerformanceCycle, { foreignKey: 'cycleId', as: 'cycle' });
PerformanceReview.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
PerformanceReview.belongsTo(User, { foreignKey: 'reviewerId', as: 'reviewer' });
PerformanceReview.hasMany(PerformanceReviewScore, { foreignKey: 'reviewId', as: 'scores' });
PerformanceReviewScore.belongsTo(PerformanceReview, { foreignKey: 'reviewId', as: 'review' });
PerformanceReviewScore.belongsTo(PerformanceCriterion, { foreignKey: 'criterionId', as: 'criterion' });
PerformanceScoreSnapshot.belongsTo(PerformanceCycle, { foreignKey: 'cycleId', as: 'cycle' });
PerformanceScoreSnapshot.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
PerformanceScoreSnapshot.belongsTo(User, { foreignKey: 'generatedBy', as: 'generator' });
PerformanceRatingBand.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
PerformanceEquivalenceSetting.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
PerformanceEquivalenceSetting.belongsTo(User, { foreignKey: 'updatedBy', as: 'updater' });
PerformanceEquivalenceGroup.belongsTo(PerformanceCycle, { foreignKey: 'cycleId', as: 'cycle' });
PerformanceEquivalenceGroup.hasMany(PerformanceEquivalenceMember, { foreignKey: 'groupId', as: 'members' });
PerformanceEquivalenceMember.belongsTo(PerformanceEquivalenceGroup, { foreignKey: 'groupId', as: 'group' });
PerformanceEquivalenceMember.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
PerformanceSignatureRule.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
PerformanceSignature.belongsTo(PerformanceCycle, { foreignKey: 'cycleId', as: 'cycle' });
PerformanceSignature.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
PerformanceSignature.belongsTo(PerformanceSignatureRule, { foreignKey: 'signatureRuleId', as: 'rule' });
PerformanceSignature.belongsTo(User, { foreignKey: 'generatedBy', as: 'generator' });
PromotionProfile.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
PromotionProfile.belongsTo(User, { foreignKey: 'createdBy', as: 'creator' });
PromotionProfile.hasMany(PromotionReadinessCriterion, { foreignKey: 'profileId', as: 'criteria' });
PromotionReadinessCriterion.belongsTo(PromotionProfile, { foreignKey: 'profileId', as: 'profile' });
EmployeePromotionAssessment.belongsTo(PerformanceCycle, { foreignKey: 'cycleId', as: 'cycle' });
EmployeePromotionAssessment.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
EmployeePromotionAssessment.belongsTo(PromotionProfile, { foreignKey: 'promotionProfileId', as: 'profile' });
EmployeePromotionAssessment.belongsTo(User, { foreignKey: 'assessedBy', as: 'assessor' });
PerformanceReward.belongsTo(PerformanceCycle, { foreignKey: 'cycleId', as: 'cycle' });
PerformanceReward.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
PerformanceReward.belongsTo(User, { foreignKey: 'recommendedBy', as: 'recommender' });
PerformanceReward.belongsTo(User, { foreignKey: 'approvedBy', as: 'approver' });
PerformanceCalibrationDecision.belongsTo(PerformanceCycle, { foreignKey: 'cycleId', as: 'cycle' });
PerformanceCalibrationDecision.belongsTo(PerformanceReview, { foreignKey: 'reviewId', as: 'review' });
PerformanceCalibrationDecision.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
PerformanceCalibrationDecision.belongsTo(User, { foreignKey: 'decidedBy', as: 'decider' });
PerformanceCalibrationSetting.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
PerformanceCalibrationSetting.belongsTo(User, { foreignKey: 'updatedBy', as: 'updater' });
PerformanceAppraisalExplanation.belongsTo(PerformanceCycle, { foreignKey: 'cycleId', as: 'cycle' });
PerformanceAppraisalExplanation.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
PerformanceAppraisalExplanation.belongsTo(User, { foreignKey: 'generatedBy', as: 'generator' });
PerformanceFairnessFlag.belongsTo(PerformanceCycle, { foreignKey: 'cycleId', as: 'cycle' });
PerformanceFairnessFlag.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
PerformanceFairnessFlag.belongsTo(PerformanceReview, { foreignKey: 'reviewId', as: 'review' });
PerformanceFairnessFlag.belongsTo(User, { foreignKey: 'resolvedBy', as: 'resolver' });
PerformanceFairnessFlag.belongsTo(User, { foreignKey: 'generatedBy', as: 'generator' });
EmployeeDocument.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
EmployeeDocument.belongsTo(User, { foreignKey: 'uploadedBy', as: 'uploader' });
Employee.hasMany(AttendanceRecord, { foreignKey: 'employeeId', as: 'attendanceRecords' });
AttendanceRecord.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
AttendanceRecord.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
Tenant.hasMany(LeaveType, { foreignKey: 'tenantId', as: 'leaveTypes' });
Tenant.hasMany(LeaveRequest, { foreignKey: 'tenantId', as: 'leaveRequests' });
Tenant.hasMany(Notification, { foreignKey: 'tenantId', as: 'notifications' });
LeaveType.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
LeaveType.hasMany(LeaveBalance, { foreignKey: 'leaveTypeId', as: 'balances' });
LeaveType.hasMany(LeaveRequest, { foreignKey: 'leaveTypeId', as: 'requests' });
Employee.hasMany(LeaveBalance, { foreignKey: 'employeeId', as: 'leaveBalances' });
Employee.hasMany(LeaveRequest, { foreignKey: 'employeeId', as: 'leaveRequests' });
LeaveBalance.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
LeaveBalance.belongsTo(LeaveType, { foreignKey: 'leaveTypeId', as: 'leaveType' });
LeaveRequest.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
LeaveRequest.belongsTo(LeaveType, { foreignKey: 'leaveTypeId', as: 'leaveType' });
LeaveRequest.belongsTo(User, { foreignKey: 'reviewedBy', as: 'reviewer' });
Notification.belongsTo(User, { foreignKey: 'userId', as: 'user' });
Tenant.hasMany(PayrollRun, { foreignKey: 'tenantId', as: 'payrollRuns' });
PayrollRun.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
PayrollRun.belongsTo(User, { foreignKey: 'generatedBy', as: 'generator' });
PayrollRun.belongsTo(User, { foreignKey: 'approvedBy', as: 'approver' });
PayrollRun.hasMany(PayrollItem, { foreignKey: 'payrollRunId', as: 'items' });
PayrollItem.belongsTo(PayrollRun, { foreignKey: 'payrollRunId', as: 'run' });
PayrollItem.belongsTo(Employee, { foreignKey: 'employeeId', as: 'employee' });
PayrollItem.hasMany(PayrollItemLine, { foreignKey: 'payrollItemId', as: 'lines' });
PayrollItemLine.belongsTo(PayrollItem, { foreignKey: 'payrollItemId', as: 'item' });
AuditLog.belongsTo(Tenant, { foreignKey: 'tenantId', as: 'tenant' });
AuditLog.belongsTo(User, { foreignKey: 'actorUserId', as: 'actor' });

export { Tenant, TenantSetting, User, UserSession, Invitation, PasswordResetToken, Department, Employee, EmployeeSalaryStructure, SalaryComponent, EmployeeSalaryComponent, Bonus, EmployeeDeduction, EmployeeLoan, LoanInstallment, EmployeeBankAccount, EmployeeTaxConfiguration, PayrollAdjustment, PerformanceCycle, PerformanceCriterion, PerformanceTemplate, PerformanceTemplateCriterion, PerformanceGoal, PerformanceEvidence, PerformanceReview, PerformanceReviewScore, PerformanceScoreSnapshot, PerformanceRatingBand, PerformanceEquivalenceSetting, PerformanceEquivalenceGroup, PerformanceEquivalenceMember, PerformanceSignatureRule, PerformanceSignature, PromotionProfile, PromotionReadinessCriterion, EmployeePromotionAssessment, PerformanceReward, PerformanceCalibrationDecision, PerformanceCalibrationSetting, PerformanceAppraisalExplanation, PerformanceFairnessFlag, EmployeeDocument, AttendanceRecord, LeaveType, LeaveBalance, LeaveRequest, Notification, PayrollRun, PayrollItem, PayrollItemLine, AuditLog, EmployeeHistoryEvent, HistoricalPerformanceRecord, PerformanceCycleLink };
