import { Router } from 'express';
import { authenticate } from '../../middleware/authenticate.js';
import { authorize } from '../../middleware/authorize.js';
import { validate } from '../../middleware/validate.js';
import { bankAccountSchema, bonusSchema, componentAssignmentSchema, componentSchema, deductionSchema, loanApprovalSchema, loanSchema, payrollCsvQuerySchema, payrollEmployeeQuerySchema, payrollPeriodSchema, payrollRunQuerySchema, salaryStructureSchema } from './payroll.schemas.js';
import { bankCreate, bankExport, bankList, bankUpdate, bonusApprove, bonusCreate, bonusList, bonusReject, componentAssign, componentCreate, componentList, componentUpdate, csvExport, deductionCreate, deductionList, deductionUpdate, generateHandler, itemGet, itemPeriodGet, loanApprove, loanCreate, loanGet, loanInstallmentList, loanList, loanReject, myList, pdfExport, reviewGet, runApprove, runGet, runLock, runsList, salaryChange, salaryList } from './payroll.controller.js';

const router = Router();
router.use(authenticate);
router.get('/me', authorize('admin', 'employee'), validate(payrollRunQuerySchema, 'query'), myList);
router.get('/', authorize('admin'), validate(payrollRunQuerySchema, 'query'), runsList);
router.post('/generate', authorize('admin'), validate(payrollPeriodSchema), generateHandler);
router.post('/runs', authorize('admin'), validate(payrollPeriodSchema), generateHandler);
router.get('/runs', authorize('admin'), validate(payrollRunQuerySchema, 'query'), runsList);
router.get('/runs/:id', authorize('admin'), runGet);
router.post('/runs/:id/approve', authorize('admin'), runApprove);
router.post('/runs/:id/lock', authorize('admin'), runLock);
router.get('/runs/:id/review', authorize('admin'), reviewGet);
router.get('/runs/:id/export/bank', authorize('admin'), bankExport);
router.get('/export/csv', authorize('admin'), validate(payrollCsvQuerySchema, 'query'), csvExport);
router.get('/salary-structures', authorize('admin'), salaryList);
router.get('/salary-structures/:employeeId', authorize('admin'), salaryList);
router.post('/salary-structures/:employeeId/change', authorize('admin'), validate(salaryStructureSchema), salaryChange);
router.get('/components', authorize('admin'), componentList);
router.post('/components', authorize('admin'), validate(componentSchema), componentCreate);
router.patch('/components/:id', authorize('admin'), validate(componentSchema.partial()), componentUpdate);
router.post('/components/:componentId/employees/:employeeId', authorize('admin'), validate(componentAssignmentSchema), componentAssign);
router.get('/bonuses', authorize('admin'), validate(payrollEmployeeQuerySchema, 'query'), bonusList);
router.post('/bonuses', authorize('admin'), validate(bonusSchema), bonusCreate);
router.post('/bonuses/:id/approve', authorize('admin'), bonusApprove);
router.post('/bonuses/:id/reject', authorize('admin'), bonusReject);
router.get('/deductions', authorize('admin'), validate(payrollEmployeeQuerySchema, 'query'), deductionList);
router.post('/deductions', authorize('admin'), validate(deductionSchema), deductionCreate);
router.patch('/deductions/:id', authorize('admin'), validate(deductionSchema.partial()), deductionUpdate);
router.get('/loans', authorize('admin'), loanList);
router.get('/loans/:id', authorize('admin'), loanGet);
router.post('/loans', authorize('admin'), validate(loanSchema), loanCreate);
router.post('/loans/:id/approve', authorize('admin'), validate(loanApprovalSchema), loanApprove);
router.post('/loans/:id/reject', authorize('admin'), loanReject);
router.get('/loans/:id/installments', authorize('admin'), loanInstallmentList);
router.get('/bank-accounts/:employeeId', authorize('admin'), bankList);
router.post('/bank-accounts/:employeeId', authorize('admin'), validate(bankAccountSchema), bankCreate);
router.patch('/bank-accounts/:id', authorize('admin'), validate(bankAccountSchema.partial()), bankUpdate);
router.get('/items/:id/payslip', authorize('admin', 'employee'), itemGet);
router.get('/items/:id/pdf', authorize('admin', 'employee'), pdfExport);
router.get('/:employeeId/:month/:year', authorize('admin', 'employee'), itemPeriodGet);

export default router;
