import { Op } from 'sequelize';
import { sequelize } from '../../config/database.js';
import { AppError } from '../../middleware/error.js';
import { recordAudit } from '../../services/audit.service.js';
import { Employee, EmployeeBankAccount, EmployeeDeduction, EmployeeLoan, EmployeeSalaryComponent, EmployeeSalaryStructure, Bonus, LoanInstallment, SalaryComponent } from '../../database/models/index.js';

const periodWhere = (start, end) => ({ effectiveFrom: { [Op.lte]: end }, [Op.or]: [{ effectiveTo: null }, { effectiveTo: { [Op.gte]: start } }] });
const employeeWhere = (auth, employeeId) => ({ id: employeeId, tenantId: auth.tenantId });
const findEmployee = async (auth, employeeId) => { const employee = await Employee.findOne({ where: employeeWhere(auth, employeeId) }); if (!employee) throw new AppError('Employee not found', 404, 'EMPLOYEE_NOT_FOUND'); return employee; };
const money = (value) => { const text = String(value ?? '0'); if (!/^\d+(\.\d{1,2})?$/.test(text)) throw new AppError('Money values must be non-negative decimal amounts', 422, 'INVALID_MONEY'); return Number(text).toFixed(2); };

export async function listSalaryStructures(auth, employeeId = null) { const where = { tenantId: auth.tenantId, ...(employeeId ? { employeeId } : {}) }; return EmployeeSalaryStructure.findAll({ where, order: [['employeeId', 'ASC'], ['effectiveFrom', 'DESC']] }); }
export async function changeSalaryStructure(auth, employeeId, input) {
  await findEmployee(auth, employeeId);
  return sequelize.transaction(async (transaction) => {
    const current = await EmployeeSalaryStructure.findOne({ where: { tenantId: auth.tenantId, employeeId, effectiveFrom: { [Op.lt]: input.effectiveFrom }, [Op.or]: [{ effectiveTo: null }, { effectiveTo: { [Op.gte]: input.effectiveFrom } }] }, order: [['effectiveFrom', 'DESC']], transaction, lock: transaction.LOCK.UPDATE });
    if (current) { const end = new Date(`${input.effectiveFrom}T00:00:00Z`); end.setUTCDate(end.getUTCDate() - 1); current.effectiveTo = end.toISOString().slice(0, 10); await current.save({ transaction }); }
    const created = await EmployeeSalaryStructure.create({ tenantId: auth.tenantId, employeeId, createdBy: auth.userId, ...input, baseSalary: money(input.baseSalary), houseAllowance: money(input.houseAllowance), transportAllowance: money(input.transportAllowance), medicalAllowance: money(input.medicalAllowance), taxDeduction: money(input.taxDeduction), otherDeductions: money(input.otherDeductions) }, { transaction });
    await recordAudit({ tenantId: auth.tenantId, actorUserId: auth.userId, action: 'salary_structure_changed', entityType: 'employee_salary_structure', entityId: created.id, afterData: created.toJSON(), transaction });
    return created;
  });
}
export async function listComponents(auth) { return SalaryComponent.findAll({ where: { tenantId: auth.tenantId }, include: [{ model: EmployeeSalaryComponent, as: 'assignments', attributes: ['id', 'employeeId', 'amount', 'percentage', 'effectiveFrom', 'effectiveTo', 'isActive'] }], order: [['name', 'ASC']] }); }
export async function createComponent(auth, input) { const component = await SalaryComponent.create({ tenantId: auth.tenantId, ...input, code: input.code.toUpperCase() }); await recordAudit({ tenantId: auth.tenantId, actorUserId: auth.userId, action: 'salary_component_created', entityType: 'salary_component', entityId: component.id, afterData: component.toJSON() }); return component; }
export async function updateComponent(auth, id, input) { const component = await SalaryComponent.findOne({ where: { id, tenantId: auth.tenantId } }); if (!component) throw new AppError('Salary component not found', 404, 'COMPONENT_NOT_FOUND'); await component.update(input); return component; }
export async function assignComponent(auth, employeeId, componentId, input) { await findEmployee(auth, employeeId); const component = await SalaryComponent.findOne({ where: { id: componentId, tenantId: auth.tenantId, isActive: true } }); if (!component) throw new AppError('Salary component not found', 404, 'COMPONENT_NOT_FOUND'); return EmployeeSalaryComponent.create({ tenantId: auth.tenantId, employeeId, componentId, ...input }); }

export async function listBonuses(auth, query = {}) { return Bonus.findAll({ where: { tenantId: auth.tenantId, ...(query.employeeId ? { employeeId: query.employeeId } : {}), ...(query.status ? { status: query.status } : {}) }, include: [{ model: Employee, as: 'employee', attributes: ['id', 'employeeCode'] }], order: [['payrollYear', 'DESC'], ['payrollMonth', 'DESC'], ['createdAt', 'DESC']] }); }
export async function createBonus(auth, input) { await findEmployee(auth, input.employeeId); return Bonus.create({ tenantId: auth.tenantId, createdBy: auth.userId, ...input, amount: money(input.amount) }); }
export async function setBonusStatus(auth, id, status) { const bonus = await Bonus.findOne({ where: { id, tenantId: auth.tenantId } }); if (!bonus) throw new AppError('Bonus not found', 404, 'BONUS_NOT_FOUND'); if (!['draft', 'pending', 'approved', 'rejected'].includes(bonus.status)) throw new AppError('Processed bonuses cannot be changed', 409, 'BONUS_IMMUTABLE'); await bonus.update({ status, ...(status === 'approved' ? { approvedBy: auth.userId, approvedAt: new Date() } : {}) }); await recordAudit({ tenantId: auth.tenantId, actorUserId: auth.userId, action: `bonus_${status}`, entityType: 'bonus', entityId: id, afterData: bonus.toJSON() }); return bonus; }

export async function listDeductions(auth, query = {}) { return EmployeeDeduction.findAll({ where: { tenantId: auth.tenantId, ...(query.employeeId ? { employeeId: query.employeeId } : {}), ...(query.status ? { status: query.status } : {}) }, order: [['effectiveFrom', 'DESC']] }); }
export async function createDeduction(auth, input) { await findEmployee(auth, input.employeeId); return EmployeeDeduction.create({ tenantId: auth.tenantId, createdBy: auth.userId, ...input, amount: money(input.amount) }); }
export async function updateDeduction(auth, id, input) { const row = await EmployeeDeduction.findOne({ where: { id, tenantId: auth.tenantId } }); if (!row) throw new AppError('Deduction not found', 404, 'DEDUCTION_NOT_FOUND'); if (row.processedPayrollItemId) throw new AppError('Processed deductions are immutable', 409, 'DEDUCTION_IMMUTABLE'); await row.update({ ...input, ...(input.amount !== undefined ? { amount: money(input.amount) } : {}) }); return row; }

export async function listLoans(auth) { return EmployeeLoan.findAll({ where: { tenantId: auth.tenantId }, include: [{ model: Employee, as: 'employee', attributes: ['id', 'employeeCode'] }, { model: LoanInstallment, as: 'installments' }], order: [['createdAt', 'DESC']] }); }
export async function getLoan(auth, id) { const loan = await EmployeeLoan.findOne({ where: { id, tenantId: auth.tenantId }, include: [{ model: LoanInstallment, as: 'installments' }] }); if (!loan) throw new AppError('Loan not found', 404, 'LOAN_NOT_FOUND'); return loan; }
export async function createLoan(auth, input) { await findEmployee(auth, input.employeeId); return EmployeeLoan.create({ tenantId: auth.tenantId, ...input, requestedAmount: money(input.requestedAmount), status: 'pending' }); }
export async function setLoanStatus(auth, id, status, input = {}) { const loan = await getLoan(auth, id); if (loan.status !== 'pending') throw new AppError('Only pending loans can be reviewed', 409, 'LOAN_IMMUTABLE'); const approvedAmount = input.approvedAmount ?? loan.requestedAmount; const installmentAmount = input.installmentAmount ?? approvedAmount; await sequelize.transaction(async (transaction) => { const nextStatus = status === 'approved' ? 'active' : status; await loan.update({ status: nextStatus, approvedBy: status === 'approved' ? auth.userId : null, approvedAt: status === 'approved' ? new Date() : null, approvedAmount: status === 'approved' ? money(approvedAmount) : null, installmentAmount: status === 'approved' ? money(installmentAmount) : null, outstandingBalance: status === 'approved' ? money(approvedAmount) : null, numberOfInstallments: status === 'approved' ? input.numberOfInstallments : null, startMonth: status === 'approved' ? input.startMonth : null, startYear: status === 'approved' ? input.startYear : null }, { transaction }); if (status === 'approved' && input.numberOfInstallments && input.startMonth && input.startYear) { const start = new Date(Date.UTC(input.startYear, input.startMonth - 1, 1)); const rows = Array.from({ length: input.numberOfInstallments }, (_, index) => { const date = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth() + index, 1)); return { tenantId: auth.tenantId, loanId: loan.id, installmentMonth: date.getUTCMonth() + 1, installmentYear: date.getUTCFullYear(), amount: money(installmentAmount), status: 'pending' }; }); await LoanInstallment.bulkCreate(rows, { transaction }); } }); return getLoan(auth, id); }
export async function loanInstallments(auth, id) { await getLoan(auth, id); return LoanInstallment.findAll({ where: { tenantId: auth.tenantId, loanId: id }, order: [['installmentYear', 'ASC'], ['installmentMonth', 'ASC']] }); }

export async function listBankAccounts(auth, employeeId) { await findEmployee(auth, employeeId); return EmployeeBankAccount.findAll({ where: { tenantId: auth.tenantId, employeeId }, attributes: { exclude: ['accountNumber', 'iban'] }, order: [['isPrimary', 'DESC'], ['createdAt', 'DESC']] }); }
export async function createBankAccount(auth, employeeId, input) { await findEmployee(auth, employeeId); return sequelize.transaction(async (transaction) => { if (input.isPrimary) await EmployeeBankAccount.update({ isPrimary: false }, { where: { tenantId: auth.tenantId, employeeId }, transaction }); return EmployeeBankAccount.create({ tenantId: auth.tenantId, employeeId, ...input }, { transaction }); }); }
export async function updateBankAccount(auth, id, input) { const account = await EmployeeBankAccount.findOne({ where: { id, tenantId: auth.tenantId } }); if (!account) throw new AppError('Bank account not found', 404, 'BANK_ACCOUNT_NOT_FOUND'); return sequelize.transaction(async (transaction) => { if (input.isPrimary) await EmployeeBankAccount.update({ isPrimary: false }, { where: { tenantId: auth.tenantId, employeeId: account.employeeId }, transaction }); await account.update(input, { transaction }); return account; }); }
