import { useEffect, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { dashboardService } from '../../services/dashboardService.js';
import LoadingState from '../../components/common/LoadingState.jsx';
import ErrorState from '../../components/common/ErrorState.jsx';
import StatusBadge from '../../components/common/StatusBadge.jsx';

const colors = ['#7265e6', '#51aa83', '#d69d30', '#dd7591', '#5c9bd5'];

export default function DashboardPage({ user }) {
  const role = user?.user?.role || 'admin';
  const [data, setData] = useState(null); const [error, setError] = useState('');
  async function load() { setError(''); try { const requests = [dashboardService.summary(), dashboardService.attendanceTrend(), dashboardService.activity()]; if (role === 'admin' || role === 'manager') requests.push(dashboardService.headcount()); if (role === 'admin') requests.push(dashboardService.payrollTrend()); const [summary, attendance, activity, headcount, payroll] = await Promise.all(requests); setData({ summary, attendance, activity, headcount: role === 'admin' || role === 'manager' ? headcount : [], payroll: role === 'admin' ? payroll : [] }); } catch (requestError) { setError(requestError.response?.data?.error?.message || 'Unable to load dashboard data.'); } }
  useEffect(() => { load(); }, [role]);
  if (error) return <ErrorState message={error} onRetry={load} />;
  if (!data) return <LoadingState label="Loading dashboard…" />;
  return role === 'employee' ? <EmployeeDashboard data={data} user={user} /> : <ManagementDashboard data={data} role={role} user={user} />;
}

function DashboardHeader({ user, role }) { return <div className="page-heading dashboard-heading"><div><div className="eyebrow">{role === 'admin' ? 'Company overview' : 'Team overview'}</div><h1>Good morning, {user?.user?.name?.split(' ')[0] || 'there'} <span className="wave">✦</span></h1><p>Here’s what’s happening across your workspace today.</p></div></div>; }
function Kpi({ label, value, detail, tone = 'violet' }) { return <div className="kpi-card"><div className={`kpi-icon ${tone}`} /> <small>{label}</small><strong>{value}</strong><span className={tone === 'mint' ? 'positive' : ''}>{detail}</span></div>; }

function ManagementDashboard({ data, role, user }) {
  const s = data.summary; const attendance = data.attendance.map(item => ({ ...item, label: item.month.slice(5) }));
  return <><DashboardHeader user={user} role={role} /><div className="kpi-grid"><Kpi label={role === 'admin' ? 'Total employees' : 'Team members'} value={s.totalEmployees} detail={`${s.attendanceRateToday}% attendance today`} /><Kpi label="Present today" value={s.presentToday} detail="Present or late" tone="mint" /><Kpi label="On leave today" value={s.onLeaveToday} detail="Approved leave" tone="amber" /><Kpi label="Pending approvals" value={s.pendingApprovals} detail="Needs review" tone="pink" /></div><div className="dashboard-grid dashboard-chart-grid"><div className="panel"><div className="panel-heading"><div><h2>Attendance rate</h2><p>Last six months</p></div></div><div className="chart-box"><ResponsiveContainer width="100%" height={230}><LineChart data={attendance}><CartesianGrid strokeDasharray="3 3" stroke="#e7e8ed" /><XAxis dataKey="label" fontSize={11} /><YAxis domain={[0, 100]} fontSize={11} /><Tooltip /><Line type="monotone" dataKey="attendanceRate" stroke="#7265e6" strokeWidth={3} dot={{ r: 3 }} /></LineChart></ResponsiveContainer></div></div><div className="panel"><div className="panel-heading"><div><h2>Department headcount</h2><p>Current active employees</p></div></div><div className="chart-box"><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={data.headcount} dataKey="count" nameKey="department" innerRadius={55} outerRadius={85} paddingAngle={3}>{data.headcount.map((entry, index) => <Cell key={entry.department} fill={colors[index % colors.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div className="chart-legend">{data.headcount.slice(0, 5).map((item, index) => <span key={item.department}><i style={{ background: colors[index % colors.length] }} />{item.department}: {item.count}</span>)}</div></div></div><div className="dashboard-grid"><div className="panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>Latest workspace updates</p></div></div><div className="activity-list">{data.activity.slice(0, 6).map(item => <div className="activity-row" key={`${item.type}-${item.id}`}><span>{item.message}<small>{new Date(item.createdAt).toLocaleDateString()}</small></span><StatusBadge status={item.status} /></div>)}</div></div>{role === 'admin' && <div className="panel"><div className="panel-heading"><div><h2>Payroll cost</h2><p>Last six months</p></div></div><div className="chart-box"><ResponsiveContainer width="100%" height={230}><BarChart data={data.payroll}><CartesianGrid strokeDasharray="3 3" stroke="#e7e8ed" /><XAxis dataKey="month" fontSize={11} /><YAxis fontSize={11} /><Tooltip /><Bar dataKey="net" fill="#7265e6" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></div>}</div></>;
}

function EmployeeDashboard({ data, user }) { const attendance = data.attendance.map(item => ({ ...item, label: item.month.slice(5) })); const today = data.summary.today?.attendance; const payslip = data.summary.latestPayslip; return <><DashboardHeader user={user} role="employee" /><div className="kpi-grid"><Kpi label="Today’s attendance" value={today?.status || 'Not clocked'} detail={today?.clockIn ? `Clocked in at ${new Date(today.clockIn).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : 'Clock in to start your day'} tone="mint" /><Kpi label="Pending leave" value={data.summary.pendingLeaves} detail="Requests awaiting review" tone="amber" /><Kpi label="Latest payslip" value={payslip ? `${payslip.netSalary || 0}` : '—'} detail={payslip ? 'Net salary' : 'No payslip yet'} tone="violet" /></div><div className="dashboard-grid"><div className="panel"><div className="panel-heading"><div><h2>My attendance</h2><p>Monthly attendance trend</p></div></div><div className="chart-box"><ResponsiveContainer width="100%" height={240}><LineChart data={attendance}><CartesianGrid strokeDasharray="3 3" stroke="#e7e8ed" /><XAxis dataKey="label" fontSize={11} /><YAxis domain={[0, 100]} fontSize={11} /><Tooltip /><Line type="monotone" dataKey="attendanceRate" stroke="#51aa83" strokeWidth={3} /></LineChart></ResponsiveContainer></div></div><div className="panel employee-summary"><h2>Quick summary</h2><p>Use the workspace navigation to clock attendance, apply for leave, and access your payslips.</p><StatusBadge status={today?.status || 'pending'}>{today?.status || 'Not clocked in'}</StatusBadge></div></div></>; }
