import { Op } from 'sequelize';
import { sequelize } from '../../config/database.js';
import { PerformanceCriterion, PerformanceTemplate, PerformanceTemplateCriterion, User } from '../../database/models/index.js';
import { AppError } from '../../middleware/error.js';
import { recordAudit } from '../../services/audit.service.js';

function includeTemplate() { return [{ model: User, as: 'creator', attributes: ['id', 'name'] }, { model: PerformanceTemplateCriterion, as: 'criteria', include: [{ model: PerformanceCriterion, as: 'criterion' }], order: [['sortOrder', 'ASC']] }]; }
function assertScale(min, max) { if (Number(min) >= Number(max)) throw new AppError('Rating scale maximum must be greater than minimum', 422, 'INVALID_RATING_SCALE'); }
export function templateWeightTotal(rows) { return rows.reduce((total, row) => total + Math.round(Number(row.weight) * 1000), 0) / 1000; }
function weightTotal(rows) { return Math.round(templateWeightTotal(rows) * 1000); }
export function templateWeightsAreComplete(rows) { return weightTotal(rows) === 100000; }
function assertCompleteWeights(rows) { if (!templateWeightsAreComplete(rows)) throw new AppError(`Template criteria weights must total 100%. Current total: ${(templateWeightTotal(rows)).toFixed(3)}%`, 422, 'TEMPLATE_WEIGHTS_NOT_100'); }
function assertWeightsWithinLimit(rows) { if (weightTotal(rows) > 100000) throw new AppError(`Template criteria weights cannot exceed 100%. Current total: ${(templateWeightTotal(rows)).toFixed(3)}%`, 422, 'TEMPLATE_WEIGHTS_OVER_100'); }
async function templateFor(auth, id) { const template = await PerformanceTemplate.findOne({ where: { id, tenantId: auth.tenantId }, include: includeTemplate() }); if (!template) throw new AppError('Performance template not found', 404, 'PERFORMANCE_TEMPLATE_NOT_FOUND'); return template; }
function assertEditable(template) { if (template.status !== 'draft') throw new AppError('Template criteria are frozen after activation', 409, 'PERFORMANCE_TEMPLATE_FROZEN'); }

export async function listCriteria(auth) { return PerformanceCriterion.findAll({ where: { tenantId: auth.tenantId }, order: [['category', 'ASC'], ['name', 'ASC']] }); }
export async function createCriterion(auth, input) { assertScale(input.ratingScaleMin, input.ratingScaleMax); const criterion = await PerformanceCriterion.create({ tenantId: auth.tenantId, ...input }); await recordAudit({ tenantId: auth.tenantId, actorUserId: auth.userId, action: 'performance_criterion_created', entityType: 'performance_criterion', entityId: criterion.id, afterData: criterion.toJSON() }); return criterion; }
export async function updateCriterion(auth, id, input) { const criterion = await PerformanceCriterion.findOne({ where: { id, tenantId: auth.tenantId } }); if (!criterion) throw new AppError('Performance criterion not found', 404, 'PERFORMANCE_CRITERION_NOT_FOUND'); const activeUse = await PerformanceTemplateCriterion.findOne({ where: { tenantId: auth.tenantId, criterionId: id }, include: [{ model: PerformanceTemplate, as: 'template', where: { status: { [Op.ne]: 'draft' } }, attributes: ['id'] }] }); if (activeUse) throw new AppError('A criterion used by an active template cannot be changed', 409, 'PERFORMANCE_CRITERION_FROZEN'); assertScale(input.ratingScaleMin ?? criterion.ratingScaleMin, input.ratingScaleMax ?? criterion.ratingScaleMax); const before = criterion.toJSON(); await criterion.update(input); await recordAudit({ tenantId: auth.tenantId, actorUserId: auth.userId, action: 'performance_criterion_updated', entityType: 'performance_criterion', entityId: id, beforeData: before, afterData: criterion.toJSON() }); return criterion; }

export async function listTemplates(auth) { return PerformanceTemplate.findAll({ where: { tenantId: auth.tenantId }, include: includeTemplate(), order: [['name', 'ASC']] }); }
export async function getTemplate(auth, id) { return templateFor(auth, id); }
export async function createTemplate(auth, input) { assertScale(input.ratingScaleMin, input.ratingScaleMax); const template = await PerformanceTemplate.create({ tenantId: auth.tenantId, createdBy: auth.userId, ...input, status: 'draft' }); await recordAudit({ tenantId: auth.tenantId, actorUserId: auth.userId, action: 'performance_template_created', entityType: 'performance_template', entityId: template.id, afterData: template.toJSON() }); return templateFor(auth, template.id); }
export async function updateTemplate(auth, id, input) { const template = await templateFor(auth, id); if (Object.keys(input).some(key => key !== 'status')) assertEditable(template); if (input.status === 'active') { assertCompleteWeights(template.criteria); } if (input.status === 'archived' && template.status === 'draft') throw new AppError('Draft templates must be activated before archiving', 409, 'INVALID_TEMPLATE_TRANSITION'); if (input.status && !['draft', 'active', 'archived'].includes(input.status)) throw new AppError('Invalid template status', 422, 'INVALID_TEMPLATE_STATUS'); assertScale(input.ratingScaleMin ?? template.ratingScaleMin, input.ratingScaleMax ?? template.ratingScaleMax); const before = template.toJSON(); await template.update(input); await recordAudit({ tenantId: auth.tenantId, actorUserId: auth.userId, action: input.status ? `performance_template_${input.status}` : 'performance_template_updated', entityType: 'performance_template', entityId: id, beforeData: before, afterData: template.toJSON() }); return templateFor(auth, id); }
export async function addTemplateCriterion(auth, templateId, input) { const template = await templateFor(auth, templateId); assertEditable(template); const criterion = await PerformanceCriterion.findOne({ where: { id: input.criterionId, tenantId: auth.tenantId, isActive: true } }); if (!criterion) throw new AppError('Performance criterion not found or inactive', 404, 'PERFORMANCE_CRITERION_NOT_FOUND'); const exists = template.criteria.find(row => row.criterionId === input.criterionId); if (exists) throw new AppError('Criterion is already assigned to this template', 409, 'TEMPLATE_CRITERION_EXISTS'); const nextRows = [...template.criteria, input]; assertWeightsWithinLimit(nextRows); const assignment = await PerformanceTemplateCriterion.create({ tenantId: auth.tenantId, templateId, ...input, ratingScaleMin: input.ratingScaleMin ?? criterion.ratingScaleMin, ratingScaleMax: input.ratingScaleMax ?? criterion.ratingScaleMax, evidenceRequired: input.evidenceRequired ?? criterion.evidenceRequired }); await recordAudit({ tenantId: auth.tenantId, actorUserId: auth.userId, action: 'performance_template_criterion_added', entityType: 'performance_template_criterion', entityId: assignment.id, afterData: assignment.toJSON() }); return templateFor(auth, templateId); }
export async function updateTemplateCriterion(auth, templateId, criterionId, input) { const template = await templateFor(auth, templateId); assertEditable(template); const assignment = await PerformanceTemplateCriterion.findOne({ where: { id: criterionId, tenantId: auth.tenantId, templateId } }); if (!assignment) throw new AppError('Template criterion assignment not found', 404, 'TEMPLATE_CRITERION_NOT_FOUND'); const rows = template.criteria.map(row => row.id === assignment.id ? { ...row.toJSON(), ...input } : row); assertWeightsWithinLimit(rows); const before = assignment.toJSON(); await assignment.update(input); await recordAudit({ tenantId: auth.tenantId, actorUserId: auth.userId, action: 'performance_template_criterion_updated', entityType: 'performance_template_criterion', entityId: assignment.id, beforeData: before, afterData: assignment.toJSON() }); return templateFor(auth, templateId); }
export async function removeTemplateCriterion(auth, templateId, criterionId) { const template = await templateFor(auth, templateId); assertEditable(template); const assignment = await PerformanceTemplateCriterion.findOne({ where: { id: criterionId, tenantId: auth.tenantId, templateId } }); if (!assignment) throw new AppError('Template criterion assignment not found', 404, 'TEMPLATE_CRITERION_NOT_FOUND'); const rows = template.criteria.filter(row => row.id !== assignment.id); if (rows.length) assertCompleteWeights(rows); await assignment.destroy(); await recordAudit({ tenantId: auth.tenantId, actorUserId: auth.userId, action: 'performance_template_criterion_removed', entityType: 'performance_template_criterion', entityId: criterionId }); return templateFor(auth, templateId); }
