import { Op } from 'sequelize';
import { Employee, PerformanceCalibrationDecision, PerformanceEquivalenceGroup, PerformanceEquivalenceMember, PerformanceFairnessFlag, PerformanceReview, PerformanceReward, PerformanceScoreSnapshot, User } from '../../database/models/index.js';
import { sequelize } from '../../config/database.js';
import { AppError } from '../../middleware/error.js';
import { recordAudit } from '../../services/audit.service.js';

export function buildFairnessFlags({ snapshots, reviews, decisions, groups, rewards }) {
  const flags = []; const reviewByEmployee = new Map(); reviews.forEach(review => reviewByEmployee.set(`${review.cycleId}:${review.employeeId}:${review.reviewType}`, review)); const decisionByReview = new Map(decisions.map(decision => [decision.reviewId, decision]));
  for (const snapshot of snapshots) {
    if (/exceptional/i.test(snapshot.ratingBand || '') && Number(snapshot.evidenceCoveragePercentage) < 25) flags.push({ employeeId: snapshot.employeeId, flagType: 'exceptional_low_evidence', severity: 'warning', message: 'Employee has an Exceptional rating but less than 25% of criteria have supporting evidence.', sourceType: 'score_snapshot', sourceId: snapshot.id, metadata: { evidenceCoveragePercentage: Number(snapshot.evidenceCoveragePercentage) } });
    const managerReview = reviewByEmployee.get(`${snapshot.cycleId}:${snapshot.employeeId}:manager`); if (managerReview && Math.abs(Number(managerReview.overallScore || 0) - Number(snapshot.finalScore)) > 10) flags.push({ employeeId: snapshot.employeeId, reviewId: managerReview.id, flagType: 'manager_score_difference', severity: 'warning', message: 'Manager review score differs from the calculated score by more than 10 points.', sourceType: 'review', sourceId: managerReview.id, metadata: { managerScore: Number(managerReview.overallScore), calculatedScore: Number(snapshot.finalScore) } });
  }
  for (const decision of decisions) { if (decision.status === 'overridden' && (!decision.justification || !decision.justification.trim())) flags.push({ employeeId: decision.employeeId, reviewId: decision.reviewId, flagType: 'override_missing_justification', severity: 'error', message: 'A manual rating override has no documented justification.', sourceType: 'calibration_decision', sourceId: decision.id }); if (decision.status === 'overridden' && Number(decision.newScore) - Number(decision.previousScore) >= 20) flags.push({ employeeId: decision.employeeId, reviewId: decision.reviewId, flagType: 'large_rating_override', severity: 'warning', message: 'Manual calibration override increased the score by 20 or more points.', sourceType: 'calibration_decision', sourceId: decision.id, metadata: { previousScore: Number(decision.previousScore), newScore: Number(decision.newScore) } }); }
  const rewardsByEmployee = new Map(); rewards.forEach(reward => { if (!rewardsByEmployee.has(reward.employeeId)) rewardsByEmployee.set(reward.employeeId, []); rewardsByEmployee.get(reward.employeeId).push(reward); });
  for (const group of groups) for (const type of new Set(group.members.flatMap(member => (rewardsByEmployee.get(member.employeeId) || []).map(reward => reward.rewardType)))) { const rows = group.members.map(member => ({ employeeId: member.employeeId, reward: (rewardsByEmployee.get(member.employeeId) || []).find(row => row.rewardType === type) })).filter(row => row.reward); if (rows.length > 1) { const values = rows.map(row => Number(row.reward.approvedValue ?? row.reward.recommendedValue)); const min = Math.min(...values); const max = Math.max(...values); if ((min === 0 && max > 0) || (min > 0 && max / min >= 1.25)) rows.forEach(row => flags.push({ employeeId: row.employeeId, flagType: 'equivalent_reward_difference', severity: 'warning', message: 'Employees in the same performance-equivalence group received substantially different reward recommendations.', sourceType: 'equivalence_group', sourceId: group.id, metadata: { rewardType: type, minimumValue: min, maximumValue: max } })); } }
  return flags;
}

async function managerEmployeeIds(auth) { const manager = await Employee.findOne({ where: { tenantId: auth.tenantId, userId: auth.userId }, attributes: ['departmentId'] }); if (!manager?.departmentId) throw new AppError('Manager is not assigned to a department', 403, 'NO_MANAGER_DEPARTMENT'); const employees = await Employee.findAll({ where: { tenantId: auth.tenantId, departmentId: manager.departmentId }, attributes: ['id'] }); return employees.map(row => row.id); }

export async function listFairnessFlags(auth, cycleId, query = {}) { const where = { tenantId: auth.tenantId, ...(cycleId ? { cycleId } : {}), ...(query.status ? { status: query.status } : {}), ...(query.severity ? { severity: query.severity } : {}) }; if (auth.role === 'manager') where.employeeId = { [Op.in]: await managerEmployeeIds(auth) }; return PerformanceFairnessFlag.findAll({ where, include: [{ model: Employee, as: 'employee', attributes: ['id', 'employeeCode'], include: [{ model: User, as: 'user', attributes: ['id', 'name'] }] }], order: [['created_at', 'DESC']] }); }

export async function generateFairnessFlags(auth, cycleId) {
  const snapshots = await PerformanceScoreSnapshot.findAll({ where: { tenantId: auth.tenantId, cycleId } }); const reviews = await PerformanceReview.findAll({ where: { tenantId: auth.tenantId, cycleId, status: { [Op.in]: ['submitted', 'released'] } } }); const decisions = await PerformanceCalibrationDecision.findAll({ where: { tenantId: auth.tenantId, cycleId } }); const rewards = await PerformanceReward.findAll({ where: { tenantId: auth.tenantId, cycleId } }); const groups = await PerformanceEquivalenceGroup.findAll({ where: { tenantId: auth.tenantId, cycleId }, include: [{ model: PerformanceEquivalenceMember, as: 'members' }] });
  return sequelize.transaction(async transaction => { await PerformanceFairnessFlag.destroy({ where: { tenantId: auth.tenantId, cycleId }, transaction }); const definitions = buildFairnessFlags({ snapshots, reviews, decisions, groups, rewards }); const rows = await PerformanceFairnessFlag.bulkCreate(definitions.map(flag => ({ ...flag, tenantId: auth.tenantId, cycleId, generatedBy: auth.userId })), { transaction }); await recordAudit({ tenantId: auth.tenantId, actorUserId: auth.userId, action: 'performance_fairness_flags_generated', entityType: 'performance_cycle', entityId: cycleId, afterData: { flagCount: rows.length }, transaction }); return { cycleId, flagCount: rows.length, flags: rows }; });
}

export async function resolveFairnessFlag(auth, id, input) { const flag = await PerformanceFairnessFlag.findOne({ where: { id, tenantId: auth.tenantId } }); if (!flag) throw new AppError('Fairness flag not found', 404, 'FAIRNESS_FLAG_NOT_FOUND'); const before = flag.toJSON(); await flag.update({ status: input.status, resolvedBy: auth.userId, resolvedAt: new Date(), resolutionNote: input.resolutionNote }); await recordAudit({ tenantId: auth.tenantId, actorUserId: auth.userId, action: 'performance_fairness_flag_resolved', entityType: 'performance_fairness_flag', entityId: id, beforeData: before, afterData: flag.toJSON() }); return flag; }
