import { mkdirSync } from 'node:fs';
import path from 'node:path';
import multer from 'multer';
import { Router } from 'express';
import { env } from '../../config/env.js';
import { authenticate } from '../../middleware/authenticate.js';
import { authorize } from '../../middleware/authorize.js';
import { validate } from '../../middleware/validate.js';
import { criteriaList, criterionCreate, criterionUpdate, cycleCreate, cycleGet, cycleScoresCalculate, cyclesList, cycleUpdate, employeeEvidenceList, employeeGoalsList, employeeScoreGet, evidenceCreate, evidenceList, evidenceVerify, goalCreate, goalGet, goalsList, goalUpdate, reviewCreate, reviewGet, reviewsList, reviewSubmit, templateCreate, templateCriterionAdd, templateCriterionRemove, templateCriterionUpdate, templateGet, templatesList, templateUpdate } from './performance.controller.js';
import { performanceCriterionCreateSchema, performanceCriterionUpdateSchema, performanceCycleCreateSchema, performanceCycleQuerySchema, performanceCycleUpdateSchema, performanceEvidenceCreateSchema, performanceEvidenceQuerySchema, performanceEvidenceVerifySchema, performanceGoalCreateSchema, performanceGoalQuerySchema, performanceGoalUpdateSchema, performanceReviewCreateSchema, performanceReviewQuerySchema, performanceScoreQuerySchema, performanceTemplateCreateSchema, performanceTemplateUpdateSchema, templateCriterionSchema, templateCriterionUpdateSchema } from './performance.schemas.js';

const router = Router();
const evidenceUploadRoot = path.resolve(env.FILE_STORAGE_ROOT, 'performance-evidence');
mkdirSync(evidenceUploadRoot, { recursive: true });
const evidenceUpload = multer({ storage: multer.diskStorage({ destination: evidenceUploadRoot, filename: (req, file, cb) => cb(null, `${Date.now()}-${file.originalname.replace(/[^a-zA-Z0-9._-]/g, '_')}`) }), limits: { fileSize: env.FILE_MAX_BYTES }, fileFilter: (req, file, cb) => cb(null, ['application/pdf', 'image/jpeg', 'image/png'].includes(file.mimetype)) });
router.use(authenticate);
router.get('/cycles', authorize('admin', 'manager', 'employee'), validate(performanceCycleQuerySchema, 'query'), cyclesList);
router.post('/cycles', authorize('admin'), validate(performanceCycleCreateSchema), cycleCreate);
router.get('/cycles/:id', authorize('admin', 'manager', 'employee'), cycleGet);
router.patch('/cycles/:id', authorize('admin'), validate(performanceCycleUpdateSchema), cycleUpdate);
router.get('/criteria', authorize('admin', 'manager'), criteriaList);
router.post('/criteria', authorize('admin'), validate(performanceCriterionCreateSchema), criterionCreate);
router.patch('/criteria/:id', authorize('admin'), validate(performanceCriterionUpdateSchema), criterionUpdate);
router.get('/templates', authorize('admin', 'manager'), templatesList);
router.post('/templates', authorize('admin'), validate(performanceTemplateCreateSchema), templateCreate);
router.get('/templates/:id', authorize('admin', 'manager'), templateGet);
router.patch('/templates/:id', authorize('admin'), validate(performanceTemplateUpdateSchema), templateUpdate);
router.post('/templates/:id/criteria', authorize('admin'), validate(templateCriterionSchema), templateCriterionAdd);
router.patch('/templates/:id/criteria/:assignmentId', authorize('admin'), validate(templateCriterionUpdateSchema), templateCriterionUpdate);
router.delete('/templates/:id/criteria/:assignmentId', authorize('admin'), templateCriterionRemove);
router.get('/goals', authorize('admin', 'manager', 'employee'), validate(performanceGoalQuerySchema, 'query'), goalsList);
router.get('/employees/:employeeId/goals', authorize('admin', 'manager', 'employee'), validate(performanceGoalQuerySchema, 'query'), employeeGoalsList);
router.get('/goals/:id', authorize('admin', 'manager', 'employee'), goalGet);
router.post('/goals', authorize('admin', 'manager'), validate(performanceGoalCreateSchema), goalCreate);
router.patch('/goals/:id', authorize('admin', 'manager'), validate(performanceGoalUpdateSchema), goalUpdate);
router.get('/evidence', authorize('admin', 'manager', 'employee'), validate(performanceEvidenceQuerySchema, 'query'), evidenceList);
router.get('/employees/:employeeId/evidence', authorize('admin', 'manager', 'employee'), validate(performanceEvidenceQuerySchema, 'query'), employeeEvidenceList);
router.post('/evidence', authorize('admin', 'manager', 'employee'), evidenceUpload.single('file'), validate(performanceEvidenceCreateSchema, 'body'), evidenceCreate);
router.patch('/evidence/:id/verify', authorize('admin', 'manager'), validate(performanceEvidenceVerifySchema), evidenceVerify);
router.get('/reviews', authorize('admin', 'manager', 'employee'), validate(performanceReviewQuerySchema, 'query'), reviewsList);
router.post('/reviews', authorize('admin', 'manager', 'employee'), validate(performanceReviewCreateSchema), reviewCreate);
router.get('/reviews/:id', authorize('admin', 'manager', 'employee'), reviewGet);
router.post('/reviews/:id/submit', authorize('admin', 'manager', 'employee'), reviewSubmit);
router.get('/employees/:employeeId/score', authorize('admin', 'manager', 'employee'), validate(performanceScoreQuerySchema, 'query'), employeeScoreGet);
router.post('/cycles/:cycleId/calculate', authorize('admin'), cycleScoresCalculate);
export default router;
