import { Router } from 'express';
import { authenticate } from '../../middleware/authenticate.js';
import { authorize } from '../../middleware/authorize.js';
import { validate } from '../../middleware/validate.js';
import { criteriaList, criterionCreate, criterionUpdate, cycleCreate, cycleGet, cyclesList, cycleUpdate, employeeGoalsList, goalCreate, goalGet, goalsList, goalUpdate, templateCreate, templateCriterionAdd, templateCriterionRemove, templateCriterionUpdate, templateGet, templatesList, templateUpdate } from './performance.controller.js';
import { performanceCriterionCreateSchema, performanceCriterionUpdateSchema, performanceCycleCreateSchema, performanceCycleQuerySchema, performanceCycleUpdateSchema, performanceGoalCreateSchema, performanceGoalQuerySchema, performanceGoalUpdateSchema, performanceTemplateCreateSchema, performanceTemplateUpdateSchema, templateCriterionSchema, templateCriterionUpdateSchema } from './performance.schemas.js';

const router = Router();
router.use(authenticate);
router.get('/cycles', authorize('admin', 'manager', 'employee'), validate(performanceCycleQuerySchema, 'query'), cyclesList);
router.post('/cycles', authorize('admin'), validate(performanceCycleCreateSchema), cycleCreate);
router.get('/cycles/:id', authorize('admin', 'manager', 'employee'), cycleGet);
router.patch('/cycles/:id', authorize('admin'), validate(performanceCycleUpdateSchema), cycleUpdate);
router.get('/criteria', authorize('admin', 'manager'), criteriaList);
router.post('/criteria', authorize('admin'), validate(performanceCriterionCreateSchema), criterionCreate);
router.patch('/criteria/:id', authorize('admin'), validate(performanceCriterionUpdateSchema), criterionUpdate);
router.get('/templates', authorize('admin', 'manager'), templatesList);
router.post('/templates', authorize('admin'), validate(performanceTemplateCreateSchema), templateCreate);
router.get('/templates/:id', authorize('admin', 'manager'), templateGet);
router.patch('/templates/:id', authorize('admin'), validate(performanceTemplateUpdateSchema), templateUpdate);
router.post('/templates/:id/criteria', authorize('admin'), validate(templateCriterionSchema), templateCriterionAdd);
router.patch('/templates/:id/criteria/:assignmentId', authorize('admin'), validate(templateCriterionUpdateSchema), templateCriterionUpdate);
router.delete('/templates/:id/criteria/:assignmentId', authorize('admin'), templateCriterionRemove);
router.get('/goals', authorize('admin', 'manager', 'employee'), validate(performanceGoalQuerySchema, 'query'), goalsList);
router.get('/employees/:employeeId/goals', authorize('admin', 'manager', 'employee'), validate(performanceGoalQuerySchema, 'query'), employeeGoalsList);
router.get('/goals/:id', authorize('admin', 'manager', 'employee'), goalGet);
router.post('/goals', authorize('admin', 'manager'), validate(performanceGoalCreateSchema), goalCreate);
router.patch('/goals/:id', authorize('admin', 'manager'), validate(performanceGoalUpdateSchema), goalUpdate);
export default router;
