import { mkdirSync } from 'node:fs';
import path from 'node:path';
import multer from 'multer';
import { z } from 'zod';
import { Router } from 'express';
import { env } from '../../config/env.js';
import { authenticate } from '../../middleware/authenticate.js';
import { authorize } from '../../middleware/authorize.js';
import { validate } from '../../middleware/validate.js';
import { appraisalExplanationGet, calibrationList, calibrationSettingsGet, calibrationSettingsUpdate, criteriaList, criterionCreate, criterionUpdate, cycleContinuitySummaryGet, cycleCreate, cycleExplanationsGenerate, cycleGet, cycleLinksList, cycleReviewCriteriaGet, cycleScoresCalculate, cycleSignaturesGenerate, cyclesList, cycleUpdate, employeeContinuityGet, employeeDevelopmentSignalsGet, employeeEvidenceList, employeeGoalsList, employeeHistoryGet, employeePromotionReadinessGet, employeeScoreGet, employeeSignatureGet, employeeTnaAnalyze, employeeTransparencyGet, goalCarryForward, myContinuityGet, myDevelopmentSignalsGet, performanceAuditList, performanceCompare, equivalenceGroupsList, equivalenceRecalculate, equivalenceSettingsGet, equivalenceSettingsUpdate, evidenceCreate, evidenceList, evidenceVerify, fairnessFlagResolve, fairnessFlagsGenerate, fairnessFlagsList, goalCreate, goalGet, goalsList, goalUpdate, promotionAssessmentCreate, promotionProfileCreate, promotionProfileUpdate, promotionProfilesList, ratingBandCreate, ratingBandUpdate, ratingBandsList, reviewCalibrate, reviewCreate, reviewGet, reviewsList, reviewOverride, reviewSubmit, rewardApprove, rewardCreate, rewardReject, rewardsList, signatureRuleCreate, signatureRuleUpdate, signatureRulesList, templateCreate, templateCriterionAdd, templateCriterionRemove, templateCriterionUpdate, templateGet, templatesList, templateUpdate, trainingNeedCreate, trainingNeedUpdate, trainingNeedsList } from './performance.controller.js';
import { performanceAuditQuerySchema, performanceCalibrationActionSchema, performanceCalibrationOverrideSchema, performanceCalibrationQuerySchema, performanceCalibrationRevealQuerySchema, performanceCalibrationSettingsSchema, performanceCompareSchema, performanceContinuityQuerySchema, performanceCriterionCreateSchema, performanceCriterionUpdateSchema, performanceCycleCreateSchema, performanceCycleQuerySchema, performanceCycleUpdateSchema, performanceEquivalenceQuerySchema, performanceEquivalenceSettingsSchema, performanceEvidenceCreateSchema, performanceEvidenceQuerySchema, performanceEvidenceVerifySchema, performanceExplanationQuerySchema, performanceTransparencyQuerySchema, performanceFairnessQuerySchema, performanceFairnessResolveSchema, performanceGoalCarryForwardSchema, performanceGoalCreateSchema, performanceGoalQuerySchema, performanceGoalUpdateSchema, performanceRatingBandCreateSchema, performanceRatingBandUpdateSchema, performanceReviewCreateSchema, performanceReviewQuerySchema, performanceScoreQuerySchema, performanceSignatureQuerySchema, performanceSignatureRuleCreateSchema, performanceSignatureRuleUpdateSchema, performanceTemplateCreateSchema, performanceTemplateUpdateSchema, performanceRewardApproveSchema, performanceRewardCreateSchema, performanceRewardQuerySchema, performanceRewardRejectSchema, promotionAssessmentCreateSchema, promotionProfileCreateSchema, promotionProfileUpdateSchema, promotionReadinessQuerySchema, templateCriterionSchema, templateCriterionUpdateSchema, tnaAnalysisSchema, trainingNeedCreateSchema, trainingNeedQuerySchema, trainingNeedUpdateSchema } from './performance.schemas.js';

const router = Router();
const evidenceUploadRoot = path.resolve(env.FILE_STORAGE_ROOT, 'performance-evidence');
mkdirSync(evidenceUploadRoot, { recursive: true });
const evidenceUpload = multer({ storage: multer.diskStorage({ destination: evidenceUploadRoot, filename: (req, file, cb) => cb(null, `${Date.now()}-${file.originalname.replace(/[^a-zA-Z0-9._-]/g, '_')}`) }), limits: { fileSize: env.FILE_MAX_BYTES }, fileFilter: (req, file, cb) => cb(null, ['application/pdf', 'image/jpeg', 'image/png'].includes(file.mimetype)) });
router.use(authenticate);
router.get('/me', authorize('employee'), validate(performanceTransparencyQuerySchema, 'query'), employeeTransparencyGet);
router.get('/me/continuity', authorize('employee'), validate(performanceContinuityQuerySchema, 'query'), myContinuityGet);
router.get('/me/development-signals', authorize('employee'), validate(performanceContinuityQuerySchema, 'query'), myDevelopmentSignalsGet);
router.get('/audit', authorize('admin'), validate(performanceAuditQuerySchema, 'query'), performanceAuditList);
router.get('/cycle-links', authorize('admin', 'manager', 'employee'), cycleLinksList);
router.get('/training-needs', authorize('admin', 'manager', 'employee'), validate(trainingNeedQuerySchema, 'query'), trainingNeedsList);
router.post('/training-needs', authorize('admin', 'manager'), validate(trainingNeedCreateSchema), trainingNeedCreate);
router.patch('/training-needs/:id', authorize('admin', 'manager'), validate(trainingNeedUpdateSchema), trainingNeedUpdate);
router.post('/compare', authorize('admin', 'manager'), validate(performanceCompareSchema), performanceCompare);
router.get('/cycles', authorize('admin', 'manager', 'employee'), validate(performanceCycleQuerySchema, 'query'), cyclesList);
router.post('/cycles', authorize('admin'), validate(performanceCycleCreateSchema), cycleCreate);
router.get('/cycles/:id', authorize('admin', 'manager', 'employee'), cycleGet);
router.get('/cycles/:cycleId/review-criteria', authorize('admin', 'manager', 'employee'), cycleReviewCriteriaGet);
router.get('/cycles/:cycleId/continuity-summary', authorize('admin', 'manager', 'employee'), cycleContinuitySummaryGet);
router.patch('/cycles/:id', authorize('admin'), validate(performanceCycleUpdateSchema), cycleUpdate);
router.get('/criteria', authorize('admin', 'manager', 'employee'), criteriaList);
router.post('/criteria', authorize('admin'), validate(performanceCriterionCreateSchema), criterionCreate);
router.patch('/criteria/:id', authorize('admin'), validate(performanceCriterionUpdateSchema), criterionUpdate);
router.get('/templates', authorize('admin', 'manager'), templatesList);
router.post('/templates', authorize('admin'), validate(performanceTemplateCreateSchema), templateCreate);
router.get('/templates/:id', authorize('admin', 'manager'), templateGet);
router.patch('/templates/:id', authorize('admin'), validate(performanceTemplateUpdateSchema), templateUpdate);
router.post('/templates/:id/criteria', authorize('admin'), validate(templateCriterionSchema), templateCriterionAdd);
router.patch('/templates/:id/criteria/:assignmentId', authorize('admin'), validate(templateCriterionUpdateSchema), templateCriterionUpdate);
router.delete('/templates/:id/criteria/:assignmentId', authorize('admin'), templateCriterionRemove);
router.get('/goals', authorize('admin', 'manager', 'employee'), validate(performanceGoalQuerySchema, 'query'), goalsList);
router.get('/employees/:employeeId/goals', authorize('admin', 'manager', 'employee'), validate(performanceGoalQuerySchema, 'query'), employeeGoalsList);
router.get('/employees/:employeeId/history', authorize('admin', 'manager', 'employee'), validate(performanceContinuityQuerySchema, 'query'), employeeHistoryGet);
router.get('/employees/:employeeId/continuity', authorize('admin', 'manager', 'employee'), validate(performanceContinuityQuerySchema, 'query'), employeeContinuityGet);
router.post('/employees/:employeeId/analyze-tna', authorize('admin', 'manager'), validate(tnaAnalysisSchema), employeeTnaAnalyze);
router.get('/employees/:employeeId/development-signals', authorize('admin', 'manager', 'employee'), validate(performanceContinuityQuerySchema, 'query'), employeeDevelopmentSignalsGet);
router.get('/goals/:id', authorize('admin', 'manager', 'employee'), goalGet);
router.post('/goals', authorize('admin', 'manager'), validate(performanceGoalCreateSchema), goalCreate);
router.patch('/goals/:id', authorize('admin', 'manager'), validate(performanceGoalUpdateSchema), goalUpdate);
router.post('/goals/:id/carry-forward', authorize('admin', 'manager'), validate(performanceGoalCarryForwardSchema), goalCarryForward);
router.get('/evidence', authorize('admin', 'manager', 'employee'), validate(performanceEvidenceQuerySchema, 'query'), evidenceList);
router.get('/employees/:employeeId/evidence', authorize('admin', 'manager', 'employee'), validate(performanceEvidenceQuerySchema, 'query'), employeeEvidenceList);
router.post('/evidence', authorize('admin', 'manager', 'employee'), evidenceUpload.single('file'), validate(performanceEvidenceCreateSchema, 'body'), evidenceCreate);
router.patch('/evidence/:id/verify', authorize('admin', 'manager'), validate(performanceEvidenceVerifySchema), evidenceVerify);
router.get('/reviews', authorize('admin', 'manager', 'employee'), validate(performanceReviewQuerySchema, 'query'), reviewsList);
router.post('/reviews', authorize('admin', 'manager', 'employee'), validate(performanceReviewCreateSchema), reviewCreate);
router.get('/reviews/:id', authorize('admin', 'manager', 'employee'), reviewGet);
router.post('/reviews/:id/submit', authorize('admin', 'manager', 'employee'), reviewSubmit);
router.get('/employees/:employeeId/score', authorize('admin', 'manager', 'employee'), validate(performanceScoreQuerySchema, 'query'), employeeScoreGet);
router.post('/cycles/:cycleId/calculate', authorize('admin'), validate(z.object({ force: z.coerce.boolean().optional().default(false) }), 'query'), cycleScoresCalculate);
router.get('/rating-bands', authorize('admin', 'manager', 'employee'), ratingBandsList);
router.post('/rating-bands', authorize('admin'), validate(performanceRatingBandCreateSchema), ratingBandCreate);
router.patch('/rating-bands/:id', authorize('admin'), validate(performanceRatingBandUpdateSchema), ratingBandUpdate);
router.get('/equivalence-settings', authorize('admin', 'manager'), equivalenceSettingsGet);
router.patch('/equivalence-settings', authorize('admin'), validate(performanceEquivalenceSettingsSchema), equivalenceSettingsUpdate);
router.get('/cycles/:cycleId/equivalence-groups', authorize('admin', 'manager'), equivalenceGroupsList);
router.post('/cycles/:cycleId/recalculate-equivalence', authorize('admin'), equivalenceRecalculate);
router.get('/signature-rules', authorize('admin', 'manager'), signatureRulesList);
router.post('/signature-rules', authorize('admin'), validate(performanceSignatureRuleCreateSchema), signatureRuleCreate);
router.patch('/signature-rules/:id', authorize('admin'), validate(performanceSignatureRuleUpdateSchema), signatureRuleUpdate);
router.get('/employees/:employeeId/signature', authorize('admin', 'manager', 'employee'), validate(performanceSignatureQuerySchema, 'query'), employeeSignatureGet);
router.post('/cycles/:cycleId/generate-signatures', authorize('admin'), cycleSignaturesGenerate);
router.get('/promotion-profiles', authorize('admin', 'manager'), promotionProfilesList);
router.post('/promotion-profiles', authorize('admin'), validate(promotionProfileCreateSchema), promotionProfileCreate);
router.patch('/promotion-profiles/:id', authorize('admin'), validate(promotionProfileUpdateSchema), promotionProfileUpdate);
router.post('/promotion-assessments', authorize('admin', 'manager'), validate(promotionAssessmentCreateSchema), promotionAssessmentCreate);
router.get('/employees/:employeeId/promotion-readiness', authorize('admin', 'manager', 'employee'), validate(promotionReadinessQuerySchema, 'query'), employeePromotionReadinessGet);
router.get('/rewards', authorize('admin', 'manager'), validate(performanceRewardQuerySchema, 'query'), rewardsList);
router.post('/rewards', authorize('admin', 'manager'), validate(performanceRewardCreateSchema), rewardCreate);
router.post('/rewards/:id/approve', authorize('admin'), validate(performanceRewardApproveSchema), rewardApprove);
router.post('/rewards/:id/reject', authorize('admin'), validate(performanceRewardRejectSchema), rewardReject);
router.get('/cycles/:cycleId/calibration', authorize('admin', 'manager'), validate(performanceCalibrationRevealQuerySchema, 'query'), calibrationList);
router.post('/reviews/:reviewId/calibrate', authorize('admin'), validate(performanceCalibrationActionSchema), reviewCalibrate);
router.post('/reviews/:reviewId/override', authorize('admin'), validate(performanceCalibrationOverrideSchema), reviewOverride);
router.get('/calibration-settings', authorize('admin', 'manager'), calibrationSettingsGet);
router.patch('/calibration-settings', authorize('admin'), validate(performanceCalibrationSettingsSchema), calibrationSettingsUpdate);
router.get('/employees/:employeeId/appraisal-explanation', authorize('admin', 'manager', 'employee'), validate(performanceExplanationQuerySchema, 'query'), appraisalExplanationGet);
router.post('/cycles/:cycleId/generate-explanations', authorize('admin'), cycleExplanationsGenerate);
router.get('/cycles/:cycleId/fairness-flags', authorize('admin', 'manager'), validate(performanceFairnessQuerySchema, 'query'), fairnessFlagsList);
router.post('/cycles/:cycleId/generate-fairness-flags', authorize('admin'), fairnessFlagsGenerate);
router.patch('/fairness-flags/:id', authorize('admin'), validate(performanceFairnessResolveSchema), fairnessFlagResolve);
export default router;
